site_name: MEV Futures
site_url: https://mevauction.com
site_description: >-
  MEV Auction documentation.
site_author: MEV.io
copyright: Manifold Finance, Inc and its contributors. 

repo _name: MEV-Protocol/platform-docs
repo_url: https://github.com/MEV-Protocol/platform-docs

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.footer
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    scheme: black
  font:
    text: 'Source Sans 3'
    code: 'Source Code Pro'

extra:
  support:
    chat: #
    email: #
    website: #
    issues: #
    doc_issues: #
  google:
    site_verification:
      - ''
    tag_manager: ''
  version:
    default:
      - stable
      - development

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - table-reader
  - tags
  # - group:
  #     enabled: !ENV CI
  #     plugins:
  #       - git-revision-date-localized
  #       - git-committers

  # - group:
  #     enabled: !ENV INSIDERS
  #     plugins:
  #       - optimize
  #       - privacy

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - overrides/stylesheets/custom_theme.css