site_name: MEV Auction
site_url: https://mevauction.com
site_description: >-
  MEV Auction documentation for builders, searchers and liquid staking protocols.
site_author: MEV.io
copyright: Manifold Finance, Inc and its contributors.

repo_name: MEV-Protocol/platform-docs
repo_url: https://github.com/MEV-Protocol/platform-docs

# Forces links in the format /help/index.html instead of mkdocs default of /help
# This allows us serve as totally static with no support from a web server
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    #    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.share
    - search.highlight
    - content.action.edit
  palette:
    scheme: black
  font:
    text: 'Inter'
    code: 'IBM Plex Sans'

extra:
  support:
    chat: #
    email: #
    website: #
    issues: #
    doc_issues: #
  google:
    site_verification:
      - ''
    tag_manager: ''
  version:
    provider: mike
    default:
      - stable
      - development
  generator: false

markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      lang: en
      # yamllint disable-line rule:line-length
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      pipeline:
        - stopWordFilter
        - trimmer
  - table-reader
  - tags
  # - group:
  #     enabled: !ENV CI
  #     plugins:
  #       - git-revision-date-localized
  #       - git-committers

  # - group:
  #     enabled: !ENV INSIDERS
  #     plugins:
  #       - optimize
  #       - privacy
  - git-revision-date-localized:
      enable_creation_date: false
  - render_swagger
  - mike

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js

extra_css:
  - overrides/stylesheets/custom_theme.css

nav:
  - Home: './index.md'
  - Developers:
      - 'Getting Started': 'Developers/index.md'
      - 'Auctioneer': 'Developers/auctioneer.md'
      - 'SDK': 'Developers/sdk.md'
      - 'Interface': 'Developers/interface.md'
      - 'Testnet': 'Developers/testnet.md'
  - Learning:
      - 'Auction Design': 'Learning/aup_auction.md'
      - 'Primary Market': 'Learning/primary-market.md'
      - 'Secondary Market': 'Learning/secondary-market.md'
      - 'Payment Methods': 'Learning/payment-methods.md'
      - 'Types of Auctions': 'Learning/types_of_auctions.md'
      - 'Rulebook': 'Learning/rulebook.md'
  - Validators:
      - 'Overview': 'Validators/index.md'
      - 'Accounting,': 'Validators/accounting,.md'
      - 'Relay': 'Validators/relay.md'
  - Relay:
      - 'Captive Insurance': 'Relay/captive-insurance.md'
  - API:
      - 'RPC': 'api/index.md'
      - 'Relay': 'api/relay.md'
      - 'Signature Scheme': 'api/signature-scheme.md'
      - 'Swagger Explorer': 'api/swagger.html'
  - Reference:
      - 'Contract Design': 'Reference/contract_design.md'
      - 'Contract Summary': 'Reference/contract_summary.md'
      - 'Glossary': 'Reference/glossary.md'
      - 'RPC Payload': 'Reference/rpc-payload.md'
      - 'ERC 6909': 'Reference/erc6909.md'