site_name: MEV Auction
site_url: https://mevauction.com
site_description: >-
  MEV Auction documentation for builders, searchers and liquid staking protocols.
site_author: MEV.io
copyright: Manifold Finance, Inc and its contributors.

repo_name: MEV-Protocol/platform-docs
repo_url: https://github.com/MEV-Protocol/platform-docs

# Forces links in the format /help/index.html instead of mkdocs default of /help
# This allows us serve as totally static with no support from a web server
use_directory_urls: false

theme:
  name: material
  features:
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    #    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    scheme: black
  font:
    text: 'Source Sans 3'
    code: 'Source Code Pro'

extra:
  support:
    chat: #
    email: #
    website: #
    issues: #
    doc_issues: #
  google:
    site_verification:
      - ''
    tag_manager: ''
  version:
    default:
      - stable
      - development
  generator: false

markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
      # yamllint disable-line rule:line-length
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      pipeline:
        - stopWordFilter
        - trimmer
  - table-reader
  - tags
  # - group:
  #     enabled: !ENV CI
  #     plugins:
  #       - git-revision-date-localized
  #       - git-committers

  # - group:
  #     enabled: !ENV INSIDERS
  #     plugins:
  #       - optimize
  #       - privacy
  - git-revision-date-localized:
      enable_creation_date: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # yamllint disable-line rule:line-length
  #  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/shortcuts.js

extra_css:
  - overrides/stylesheets/custom_theme.css

nav:
  - Home: ' ./'
  - Developers:
      - ' Getting Started': 'Developers/index.md'
      - ' Auctioneer': 'Developers/auctioneer.md'
      - ' SDK': 'Developers/sdk.md'
      - ' Testnet': 'Developers/testnet.md'
  - Learning:
      - ' Auction Design': 'Learning/aup_auction.md'
      - ' Primary Market': 'Learning/primary-market.md'
      - ' Rulebook': 'Learning/rulebook.md'
      - ' Secondary Market': 'Learning/secondary-market.md'
      - ' Types of Auctions': 'Learning/types_of_auctions.md'
  - Validators:
      - ' Accounting,': 'Validators/accounting,.md'
      - ' Overview': 'Validators/overview.md'
      - ' Relay': 'Validators/relay.md'
  - Reference:
      - ' Contract Design': 'Reference/contract_design.md'
      - ' Contract Summary': 'Reference/contract_summary.md'
      - ' Glossary': 'Reference/glossary.md'
      - ' RPC Payload': 'Reference/rpc-payload.md'
