repo_name: MEV-Protocol/platform-docs
repo_url: https://github.com/MEV-Protocol/platform-docs
site_author: MEV.io
site_description: MEV Auction documentation for builders, searchers and liquid staking protocols.
site_name: MEV Auction
site_url: https://mevauction.com
copyright: Manifold Finance, Inc and its contributors. Creative Commons Attribution-NonCommercial-NoDerivs 2.5

extra:
  generator: false
  google:
    site_verification:
    - ''
    tag_manager: ''
  support:
    chat: https://t.me/foldfinance
    doc_issues: null
    email: ops@manifoldfinance.com
    issues: null
    website: null
extra_css:
- overrides/stylesheets/custom_theme.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- javascripts/shortcuts.js

markdown_extensions:
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      name: mermaid
- admonition
- pymdownx.details
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- tables
- attr_list
- md_in_html
- abbr
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- toc:
    permalink: true
    toc_depth: 3

plugins:
- render_swagger: null
- search:
    indexing: full
    lang: en
    pipeline:
    - stopWordFilter
    - trimmer
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- table-reader
- tags

theme:
  custom_dir: overrides
  features:
  - toc.follow
  - toc.integrate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - navigation.footer
  - navigation.tabs
  - navigation.top
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.path
  - search.suggest
  - search.share
  - search.highlight
  - content.action.edit
  font:
    code: IBM Plex Sans
    text: Inter
  name: material
  palette:
    scheme: black
use_directory_urls: false

nav:
- MEV Auction: index.md
- Developers:
  - Builders & Searchers: Developers/builders.md
  - General: Developers/index.md
  - Auction Protocol: Developers/auctioneer.md
  - Interface: Developers/interface.md
  - Builder Payment Methods: Developers/payment-methods.md
  - RPC Endpoints: Developers/sdk.md
  - Test Network: Developers/testnet.md
- Learning:
  - Specification for Primary Market: Learning/aup_auction.md
  - MEV Boost: Learning/flashbots-comparison.md
  - Forward Contracts: Learning/Forward-Contracts.md
  - Secondary Market: Learning/secondary-market.md
- Clients:
  - Payment processing and finalization: Clients/accounting.md
  - How does this actually work? Who talks with whom?: Clients/clients.md
  - Mandatory Values for Validator and Beacon clients: Clients/configuration.md
  - Requirements: Clients/index.md
  - Relay: Clients/relay.md
  - Networking: Clients/validators.md
- Relay:
  - Captive Market Infrastructure Insurance: Relay/captive-insurance.md
  - Comparision: Relay/index.md
- API:
  - Beta Block: api/beta-auction.md
  - Bundle API: api/bundle.md
  - RPC Methods Available: api/index.md
  - Relay REST API: api/relay.md
  - Validator Reporting REST API: api/self-report.md
  - Custom Payload Signature Scheme for Authenticated JSON RPC Service Access: api/signature-scheme.md
- Reference:
  - Gwei values: Reference/constants.md
  - Market and Auction Design and Structure: Reference/contract_design.md
  - Primary Market: Reference/contract_summary.md
  - Functions: Reference/erc6909.md
  - Terms: Reference/glossary.md
  - Execution Layer Encoding: Reference/rpc-payload.md
- Legal:
  - Customer Due Diligence (CDD): Legal/CDD.md
  - Disclaimer: Legal/Content-Disclaimer.md
  - NFA Disclosure Statement: Legal/Disclosure-Statement.md
  - Notices and Compliance: Legal/index.md