site_name: Trident
site_url: https://sambacha.github.io/mkdocs-trident
site_description: Trident documentation.
site_author: SushiSwap community
copyright: SushiSwap Trident and its documentation are licensed under GPL-3.0 license /


theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.footer
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    scheme: black
  font:
    text: 'Source Sans 3'
    code: 'Source Code Pro'


extra:
  support:
    chat: #
    email: #
    website: #
    issues: #
    doc_issues: #
  google:
    site_verification:
      - ''
    tag_manager: ''
  version:
    default:
      - stable
      - development

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search
  - table-reader
  - tags
  # CI=1 mkdocs build
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized
        - git-committers

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize
        - privacy


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - overrides/stylesheets/custom_theme.css