
theme:
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.footer
    - navigation.tabs
    - search.suggest
    - search.highlight


  palette:
    scheme: black
  font:
    text: 'Source Sans 3'
    code: 'Source Code Pro'


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search
  - table-reader
  - tags

extra:
  version:
    default:
      - stable
      - development
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

